### ISSUE TITLE
Inconsistent download speeds with packages.microsoft.com

### ISSUE THREAD

**Issue by indy-singh** [microsoft/linux-package-repositories#196]
This morning we've had a few of our hosts hang during their regularly reimage (using ansible) when trying to install powershell.

Should it matter this is the ansible task:-

```yml
- name: Add Microsft GPG apt Key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsft Repository
  apt_repository:
    repo: deb https://packages.microsoft.com/debian/{{ ansible_distribution_major_version }}/prod {{ ansible_distribution_release }} main
    state: present

- name: Install PowerShell
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - powershell

- name: Allow powrshell ssh remoting
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Subsystem powershell /usr/bin/pwsh -sshs -NoLogo -NoProfile"
    insertafter: "^Subsystem\\s+sftp\\s+/usr/lib/openssh/sftp-server$"
  notify: reload ssh
```

We've eliminated our network speed:-

```bash
root@virtualpixielinux:/# speedtest

   Speedtest by Ookla

      Server: Cadence Networks Ltd - Haywards Heath (id: 38867)
         ISP: Connect Managed Services (UK)
Idle Latency:     7.86 ms   (jitter: 0.13ms, low: 7.80ms, high: 8.02ms)
    Download:   859.24 Mbps (data used: 1.3 GB)
                  9.84 ms   (jitter: 4.23ms, low: 7.75ms, high: 235.94ms)
      Upload:   897.00 Mbps (data used: 929.2 MB)
                 11.71 ms   (jitter: 3.36ms, low: 7.89ms, high: 238.34ms)
 Packet Loss:     0.0%
  Result URL: https://www.speedtest.net/result/c/fccf3bf4-0bc2-4f00-b3e1-e324b86c933e
````

We've managed to see the good and bad "nodes" by repeatedly running:-

```bash
curl https://packages.microsoft.com/debian/12/prod/pool/main/p/powershell/powershell_7.4.6-1.deb_amd64.deb -o NUL -D -
```

```bash
root@virtualpixielinux:/# curl https://packages.microsoft.com/debian/12/prod/pool/main/p/powershell/powershell_7.4.6-1.deb_amd64.deb -o NUL -D -
HTTP/2 200
date: Thu, 21 Nov 2024 15:09:20 GMT
content-type: application/octet-stream
content-length: 71740660
last-modified: Wed, 23 Oct 2024 22:38:23 GMT
etag: "0x8DCF3B3676ECAAE"
x-ms-request-id: 46d348b7-101e-0001-6261-3ba190000000
x-ms-version: 2024-11-04
x-ms-version-id: 2024-10-23T22:38:23.9777454Z
x-ms-is-current-version: true
x-ms-creation-time: Wed, 23 Oct 2024 22:38:23 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
content-disposition: attachment;filename=powershell_7.4.6-1.deb_amd64.deb
x-ms-server-encrypted: true
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-azure-ref: 20241121T150920Z-r1559f78f6b45bcnhC1LONg0wc00000001500000000478uf
x-cache: TCP_HIT
cache-control: public, max-age=31536000
x-fd-int-roxy-purgeid: 66950235
x-cache-info: L1_T2
accept-ranges: bytes

 11 68.4M   11 8224k    0     0  3363k      0  0:00:20  0:00:02  0:00:18 3363k^C

root@virtualpixielinux:/# curl https://packages.microsoft.com/debian/12/prod/pool/main/p/powershell/powershell_7.4.6-1.deb_amd64.deb -o NUL -D -
HTTP/2 200
date: Thu, 21 Nov 2024 15:09:23 GMT
content-type: application/octet-stream
content-length: 71740660
last-modified: Wed, 23 Oct 2024 22:38:23 GMT
etag: "0x8DCF3B3676ECAAE"
x-ms-request-id: 46d348b7-101e-0001-6261-3ba190000000
x-ms-version: 2024-11-04
x-ms-version-id: 2024-10-23T22:38:23.9777454Z
x-ms-is-current-version: true
x-ms-creation-time: Wed, 23 Oct 2024 22:38:23 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
content-disposition: attachment;filename=powershell_7.4.6-1.deb_amd64.deb
x-ms-server-encrypted: true
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-azure-ref: 20241121T150923Z-r1559f78f6bljq29hC1LON035800000002d000000003sqmq
x-cache: TCP_HIT
cache-control: public, max-age=31536000
x-fd-int-roxy-purgeid: 66950235
x-cache-info: L1_T2
accept-ranges: bytes

 11 68.4M   11 8254k    0     0  3295k      0  0:00:21  0:00:02  0:00:19 3295k^C
 
root@virtualpixielinux:/# curl https://packages.microsoft.com/debian/12/prod/pool/main/p/powershell/powershell_7.4.6-1.deb_amd64.deb -o NUL -D -
HTTP/2 200
date: Thu, 21 Nov 2024 15:09:32 GMT
content-type: application/octet-stream
content-length: 71740660
last-modified: Wed, 23 Oct 2024 22:38:23 GMT
etag: "0x8DCF3B3676ECAAE"
x-ms-request-id: 46d348b7-101e-0001-6261-3ba190000000
x-ms-version: 2024-11-04
x-ms-version-id: 2024-10-23T22:38:23.9777454Z
x-ms-is-current-version: true
x-ms-creation-time: Wed, 23 Oct 2024 22:38:23 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
content-disposition: attachment;filename=powershell_7.4.6-1.deb_amd64.deb
x-ms-server-encrypted: true
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-azure-ref: 20241121T150932Z-r1559f78f6bhhtgchC1LONayv400000002kg000000025mw0
x-cache: TCP_HIT
cache-control: public, max-age=31536000
x-fd-int-roxy-purgeid: 66950235
accept-ranges: bytes

 11 68.4M   11 8224k    0     0  3759k      0  0:00:18  0:00:02  0:00:16 3760k^C

root@virtualpixielinux:/# curl https://packages.microsoft.com/debian/12/prod/pool/main/p/powershell/powershell_7.4.6-1.deb_amd64.deb -o NUL -D -
HTTP/2 200
date: Thu, 21 Nov 2024 15:09:35 GMT
content-type: application/octet-stream
content-length: 71740660
last-modified: Wed, 23 Oct 2024 22:38:23 GMT
etag: "0x8DCF3B3676ECAAE"
x-ms-request-id: 46d348b7-101e-0001-6261-3ba190000000
x-ms-version: 2024-11-04
x-ms-version-id: 2024-10-23T22:38:23.9777454Z
x-ms-is-current-version: true
x-ms-creation-time: Wed, 23 Oct 2024 22:38:23 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
content-disposition: attachment;filename=powershell_7.4.6-1.deb_amd64.deb
x-ms-server-encrypted: true
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-azure-ref: 20241121T150935Z-r1559f78f6btxlvqhC1LON1tuc000000027g00000001argt
x-cache: TCP_HIT
cache-control: public, max-age=31536000
x-fd-int-roxy-purgeid: 66950235
accept-ranges: bytes

100 68.4M  100 68.4M    0     0  71.8M      0 --:--:-- --:--:-- --:--:-- 71.8M
```

You can see the download speeds vary massively:-

```
3363k
3295k
3760k
71.8M
```

It's very inconsistent; it goes from being okay for a few minutes (e.g. fast node) and then gets stuck on a slow node for a while.

I'm more of Windows user, so if I've done anything incorrectly or massively misunderstood what I'm seeing then please correct me :)

Cheers,
Indy
